### PR TITLE
Give the possibility to set the icon as a path instead of a string to a resource

### PR DESCRIPTION
**Pull request by Bramas**
For instance 
```java
node.setIcon(Paths.get("/absolute/path/to/image"));
```

### CODE REVIEW

**Comment by acasteigts** [comment]
This basic feature (using images from the file system) is a must be! Several people reported having trouble to add their files to the project resources. So yes, we should add the feature.

Now, as is, I find the association (String -> Resource) and (Path -> File system) quite artificial. How about maintaining a single method with a string parameter, as before, and deal with it behind the scene. One suggestion is to rely on this work flow:

if the icon property is set:
    if a resource exists with this name:
        set from resource
    else
        set from file system
else
    set default circle icon (from resource)

If you agree with this setting, could you work out a new commit ?

**Comment by Bramas** [comment]
I don't know what is the best solution, in the end you're the boss :)
I know that having a method accepting Path makes it clear that we want a path to the icon in the filesystem (almost every such functions in Java accept path and not directly string), at the same time we have to keep the method accepting string for backward compatibility. 

It's easy to accept everything, so let's do that if you want. 

Also, what if we want no icon? Maybe passing null means default icon, and passing "" means no icon and passing non existing path means default icon (with a warning). 
Or maybe null means no icon, no existing path means default icon (with warning), and we add a method setDefaultIcon() to set the default icon. What do you prefer?

**Comment by acasteigts** [comment]
OK, then let's have both function : one with a Path, the other with a String, with no semantic difference between both, that is, the Path version converts it to a String and passes it to the String method. Then, we use the work flow that I suggested above.

Regarding the rest, for now, I suggest to opt for the default icon (with warning) if neither path exists. We will get back to the no-icon feature later, with two possible distinctions : 1) keeping an transparent button to maintain drag and drop features, or 2) no button at all for better performance.

Can you implement the new patch?

**Comment by Bramas** [comment]
Ok, I've done it. I just added the fact that, if the icon filename is given as a Path, then I do not check if it exists as a Resource (and if it is given as a String, then I try the resource, and then I try the Path, and then I set the default Icon).
To do so I created so private method to help understanding the main `updateIcon` method

**Pull request merged**
